apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
        containers:
            - name: client
              image: tripti2611/complex_client
              ports:
                   - containerPort: 3050
              resources:
                  limits:
                       memory: "128Mi"
                       cpu: "500m"