version: '3'
services:
   # postgres database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    # Redis database 
    redis:
        image: 'redis:latest'
    # Api Service    
    api:
        build:
            context: ./server
        image: "tripti2611/complex_api"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
      #  Worker Service    
    worker:
        build:
            context: ./worker
        image: "tripti2611/complex_worker"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
      #  Client Service
    client:
        build:
            context: ./client
        image: "tripti2611/complex_client"
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - '3050:80'
   